name:                liquid-cuckoo-filter
version:             0.1.0.0
github:              "kubum/liquid-cuckoo-filter"
license:             BSD3
author:              "Andrey Fadeyev"
maintainer:          "fadeyew@gmail.com"
copyright:           "2019 Andrey Fadeyev"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kubum/liquid-cuckoo-filter#readme>

dependencies:
- base >= 4.7 && < 5
- vector >= 0.12.0.2
- containers
- cereal

library:
  source-dirs: src

tests:
  liquid-cuckoo-filter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - liquid-cuckoo-filter
